introduce failsafe

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -17,6 +17,15 @@
 ## CREATED: January 2024                                                            ||
 ## =================================================================================##
 
+# Fail safe in case this file is not executed from the main directory of this
+# repository.
+script_path=$(dirname "$(readlink -f "$0")")
+
+if [ ! "$(pwd)" == "$script_path" ]; then
+    echo "IMPORTANT: Please ensure that you execute the setup executable from the directory where the setup file is located."
+    exit 1
+fi
+
 parent_directory=$(dirname "$(pwd)")
 
 script_list=$(find . -type f -name "*.sh")
