feat: Remove module calls (#44)
* refactor: remove soon to be unneeded module removal

* feat: add conda installation of main dependencies

* refactor: remove module names

* chore: explain reason behind 2 conda environments

* feat: add requirements files for conda environments

* fix: ensure script is in correct directory when running

* feat: use conda environments over modules

* feat: create ldsc environment for user

If they aren't using ldsc, this just won't get used I guess.

* docs: remove mention of modules

diff --git a/Setup/setup b/Setup/setup
--- a/Setup/setup
+++ b/Setup/setup
@@ -9,6 +9,10 @@ source "${configuration_directory}/Config.txt" || \
 { echo "The configuration file does not exist in the specified location: \
 ${configuration_directory}"; exit 1; }
 
+cd "${REPO_DIR}" || \
+{ echo "The configuration file does not point to the correct script directory: \
+${REPO_DIR}"; exit 1; }
+
 ## ============================== ##
 ##   CREATION OF FILE STRUCTURE   ##
 ## ============================== ##
@@ -16,26 +20,34 @@ ${configuration_directory}"; exit 1; }
 mkdir -p  "${BINARY_DIR}" "${MODEL_DIR}" "${OPTIMUM_STATES_DIR}" \
     "${LD_ASSESSMENT_DIR}" "${BIG_MODELS_DIR}"
 
+## ====================== ##
+##   CONDA ENVIRONMENTS   ##
+## ====================== ##
+
+source "${CONDA_SHELL}" || { echo "Could not find conda shell at:
+${CONDA_SHELL}"; exit 1; }
+conda config --add channels bioconda
+conda config --add channels conda-forge
+
+conda create \
+    --name ChromOptimise-R-java \
+    --file "${REPO_DIR}/requirements-R-java.txt"
+
+# Compatible version of bedtools with R (>2.27.1) fails to process bed files
+# with genomic positions represented in scientific notation.
+conda create \
+    --name ChromOptimise-bedtools \
+    --file "${REPO_DIR}/requirements-bedtools.txt"
+
+conda create \
+    --name ldsc \
+    --file "${REPO_DIR}/requirements-ldsc.txt"
+
 ## ============================= ##
 ##   DELETE UOE SPECIFIC LINES   ##
 ## ============================= ##
 
-cd "${REPO_DIR}" || \
-{ echo "The configuration file does not point to the correct script directory: \
-${REPO_DIR}"; exit 1; }
-
 script_list=$(find . -type f -name "*.sh")
-
-echo "Do you want to remove instances of \"module load\" and \"module purge\"?"
-echo "[Recommended] (y/n)"
-read -r delete_module_lines
-
-if [[ "${delete_module_lines}" == "y" ]]; then
-    for file in $script_list; do
-        sed -i "s/module load.*//g" "${file}"
-        sed -i "s/module purge//g" "${file}"
-    done
-fi
 
 echo "Do you want to remove SLURM directives associated with UoE's HPC?"
 echo "[Recommended] (y/n)"
